plugins {
    id 'java'
    id 'application'
}

group = 'com.konasl'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

repositories {
    mavenCentral()
}

dependencies {
    // Add your dependencies here
    testImplementation 'junit:junit:4.13.2'
}

application {
    mainClass = 'com.konasl.workerplatform.Main'
}

tasks.named('test') {
    useJUnit()
}
